import type { AdminResourceConfig } from "@/lib/admin-daz/types"

const activeField = {
  name: "is_active",
  label: "Aktif",
  type: "checkbox" as const,
  defaultValue: true,
}

const sortOrderField = {
  name: "sort_order",
  label: "Urutan",
  type: "number" as const,
  min: 0,
  defaultValue: 0,
}

export const siteSettingsConfig: AdminResourceConfig = {
  table: "site_settings",
  title: "Pengaturan Situs",
  singular: "pengaturan",
  description: "Kelola informasi kontak dan konfigurasi publik berbentuk JSON.",
  primaryKey: "key",
  orderColumn: "key",
  searchFields: ["key"],
  previewFields: ["key", "value", "is_public"],
  fields: [
    {
      name: "key",
      label: "Key",
      type: "text",
      required: true,
      placeholder: "contact",
      helpText: "Gunakan huruf kecil, angka, dan tanda hubung.",
    },
    {
      name: "value",
      label: "Nilai JSON",
      type: "json",
      required: true,
      defaultValue: {},
    },
    {
      name: "is_public",
      label: "Dapat dibaca publik",
      type: "checkbox",
      defaultValue: true,
    },
    activeField,
  ],
}

export const landingSectionsConfig: AdminResourceConfig = {
  table: "landing_sections",
  title: "Section Landing Page",
  singular: "section",
  description: "Kelola heading, isi tambahan, gambar, dan urutan section.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "title", "description"],
  previewFields: ["slug", "title", "description", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "eyebrow", label: "Eyebrow", type: "text", nullable: true },
    { name: "title", label: "Judul", type: "text", required: true },
    {
      name: "highlighted_title",
      label: "Judul Sorotan",
      type: "text",
      nullable: true,
    },
    {
      name: "description",
      label: "Deskripsi",
      type: "textarea",
      nullable: true,
    },
    {
      name: "image_url",
      label: "Gambar",
      type: "image",
      nullable: true,
      bucket: "landing_page",
      folder: "sections",
    },
    {
      name: "image_alt",
      label: "Alt Gambar",
      type: "text",
      nullable: true,
    },
    {
      name: "content",
      label: "Konten Tambahan JSON",
      type: "json",
      defaultValue: {},
    },
    sortOrderField,
    activeField,
  ],
}

export const landingItemsConfig: AdminResourceConfig = {
  table: "landing_items",
  title: "Item Landing Page",
  singular: "item",
  description: "Kelola metrik, fitur, proses, dan trust point per section.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["section_slug", "slug", "title", "label"],
  filterField: "section_slug",
  previewFields: ["section_slug", "slug", "title", "label", "value", "sort_order"],
  fields: [
    {
      name: "section_slug",
      label: "Section",
      type: "select",
      required: true,
      relation: {
        table: "landing_sections",
        valueColumn: "slug",
        labelColumn: "title",
        orderColumn: "sort_order",
      },
    },
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "title", label: "Judul", type: "text", nullable: true },
    {
      name: "description",
      label: "Deskripsi",
      type: "textarea",
      nullable: true,
    },
    { name: "icon", label: "Icon ID", type: "text", nullable: true },
    { name: "label", label: "Label", type: "text", nullable: true },
    { name: "value", label: "Nilai", type: "text", nullable: true },
    {
      name: "content",
      label: "Konten Tambahan JSON",
      type: "json",
      defaultValue: {},
    },
    sortOrderField,
    activeField,
  ],
}

export const navigationItemsConfig: AdminResourceConfig = {
  table: "navigation_items",
  title: "Navigasi",
  singular: "item navigasi",
  description: "Kelola link header, mobile, CTA, dan footer.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "label", "href", "placement"],
  filterField: "placement",
  previewFields: ["placement", "label", "href", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "label", label: "Label", type: "text", required: true },
    { name: "href", label: "Tujuan Link", type: "text", required: true },
    {
      name: "placement",
      label: "Penempatan",
      type: "select",
      required: true,
      options: [
        { value: "header", label: "Header" },
        { value: "header_cta", label: "Header CTA" },
        { value: "mobile", label: "Mobile" },
        { value: "footer", label: "Footer" },
      ],
    },
    { name: "badge", label: "Badge", type: "text", nullable: true },
    { name: "icon", label: "Icon", type: "text", nullable: true },
    {
      name: "is_disabled",
      label: "Dinonaktifkan",
      type: "checkbox",
      defaultValue: false,
    },
    sortOrderField,
    activeField,
  ],
}

export const galleryItemsConfig: AdminResourceConfig = {
  table: "gallery_items",
  title: "Galeri",
  singular: "item galeri",
  description: "Kelola gambar portofolio landing page.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "label", "image_alt"],
  previewFields: ["slug", "label", "image_url", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "label", label: "Label", type: "text", required: true },
    {
      name: "image_url",
      label: "Gambar",
      type: "image",
      required: true,
      bucket: "landing_page",
      folder: "gallery",
    },
    { name: "image_alt", label: "Alt Gambar", type: "text", required: true },
    {
      name: "grid_span",
      label: "Class Grid",
      type: "text",
      placeholder: "md:row-span-2",
    },
    sortOrderField,
    activeField,
  ],
}

export const testimonialsConfig: AdminResourceConfig = {
  table: "testimonials",
  title: "Testimonial",
  singular: "testimonial",
  description: "Kelola testimonial grid dan carousel.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "name", "subtitle", "content"],
  filterField: "display_variant",
  previewFields: ["display_variant", "name", "subtitle", "rating", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    {
      name: "display_variant",
      label: "Tampilan",
      type: "select",
      required: true,
      options: [
        { value: "grid", label: "Grid" },
        { value: "carousel", label: "Carousel" },
      ],
      defaultValue: "grid",
    },
    { name: "name", label: "Nama", type: "text", required: true },
    { name: "subtitle", label: "Subjudul", type: "text", required: true },
    { name: "content", label: "Isi", type: "textarea", required: true },
    {
      name: "rating",
      label: "Rating",
      type: "number",
      required: true,
      min: 1,
      max: 5,
      defaultValue: 5,
    },
    {
      name: "avatar",
      label: "Avatar atau Emoji",
      type: "text",
      nullable: true,
    },
    sortOrderField,
    activeField,
  ],
}

export const faqsConfig: AdminResourceConfig = {
  table: "faqs",
  title: "FAQ",
  singular: "FAQ",
  description: "Kelola pertanyaan dan jawaban yang tampil di landing page.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "question", "answer"],
  previewFields: ["slug", "question", "answer", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "question", label: "Pertanyaan", type: "text", required: true },
    { name: "answer", label: "Jawaban", type: "textarea", required: true },
    sortOrderField,
    activeField,
  ],
}

export const packageTiersConfig: AdminResourceConfig = {
  table: "package_tiers",
  title: "Paket",
  singular: "paket",
  description: "Kelola tier paket yang tersedia di database.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "name", "tagline", "description"],
  previewFields: ["slug", "name", "price_label", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "name", label: "Nama", type: "text", required: true },
    { name: "tagline", label: "Tagline", type: "text", required: true },
    { name: "price_label", label: "Label Harga", type: "text", required: true },
    { name: "icon", label: "Icon ID", type: "text", required: true },
    { name: "description", label: "Deskripsi", type: "textarea", required: true },
    {
      name: "features",
      label: "Fitur",
      type: "lines",
      helpText: "Satu fitur per baris.",
      defaultValue: [],
    },
    {
      name: "is_highlighted",
      label: "Disorot",
      type: "checkbox",
      defaultValue: false,
    },
    sortOrderField,
    activeField,
  ],
}

export const productCategoriesConfig: AdminResourceConfig = {
  table: "product_categories",
  title: "Kategori Katalog",
  singular: "kategori",
  description: "Kelola kategori, emoji, status, dan urutan katalog.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "name"],
  previewFields: ["slug", "name", "emoji", "sort_order"],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    { name: "name", label: "Nama", type: "text", required: true },
    { name: "emoji", label: "Emoji", type: "text", defaultValue: "" },
    sortOrderField,
    activeField,
  ],
}

export const productsConfig: AdminResourceConfig = {
  table: "products",
  title: "Produk Katalog",
  singular: "produk",
  description: "Kelola produk, harga, gambar, badge, dan ketersediaan.",
  primaryKey: "id",
  orderColumn: "sort_order",
  searchFields: ["slug", "title", "description", "processing_time"],
  filterField: "category_slug",
  previewFields: [
    "category_slug",
    "title",
    "start_price",
    "end_price",
    "image_url",
  ],
  fields: [
    { name: "slug", label: "Slug", type: "text", required: true },
    {
      name: "category_slug",
      label: "Kategori",
      type: "select",
      required: true,
      relation: {
        table: "product_categories",
        valueColumn: "slug",
        labelColumn: "name",
        orderColumn: "sort_order",
      },
    },
    { name: "title", label: "Nama Produk", type: "text", required: true },
    { name: "description", label: "Deskripsi", type: "textarea", required: true },
    {
      name: "start_price",
      label: "Harga Awal",
      type: "number",
      required: true,
      min: 0,
    },
    {
      name: "end_price",
      label: "Harga Akhir",
      type: "number",
      nullable: true,
      min: 0,
    },
    {
      name: "image_url",
      label: "Gambar Produk",
      type: "image",
      required: true,
      bucket: "catalogs",
      folder: "products",
    },
    {
      name: "badge",
      label: "Badge",
      type: "select",
      nullable: true,
      options: [
        { value: "", label: "Tanpa badge" },
        { value: "bestseller", label: "Bestseller" },
        { value: "limited", label: "Limited" },
        { value: "loved", label: "Loved" },
      ],
    },
    {
      name: "processing_time",
      label: "Waktu Pengerjaan",
      type: "text",
      required: true,
    },
    {
      name: "is_customizable",
      label: "Dapat Dikustomisasi",
      type: "checkbox",
      defaultValue: true,
    },
    {
      name: "is_available",
      label: "Tersedia",
      type: "checkbox",
      defaultValue: true,
    },
    sortOrderField,
    activeField,
  ],
}
